/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package game;

/**
 *
 * @author Anne
 */
public class MastermindJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MastermindJFrame
     */
    public MastermindJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gamePanel = new javax.swing.JPanel();
        guess1 = new javax.swing.JPanel();
        feedbackPanel1 = new javax.swing.JPanel();
        pegCombinationPanel = new javax.swing.JPanel();
        guess2 = new javax.swing.JPanel();
        feedbackPanel2 = new javax.swing.JPanel();
        pegCombinationPanel1 = new javax.swing.JPanel();
        guess3 = new javax.swing.JPanel();
        feedbackPanel3 = new javax.swing.JPanel();
        pegCombinationPanel2 = new javax.swing.JPanel();
        guess4 = new javax.swing.JPanel();
        feedbackPanel4 = new javax.swing.JPanel();
        pegCombinationPanel3 = new javax.swing.JPanel();
        guess5 = new javax.swing.JPanel();
        feedbackPanel5 = new javax.swing.JPanel();
        pegCombinationPanel4 = new javax.swing.JPanel();
        guess6 = new javax.swing.JPanel();
        feedbackPanel6 = new javax.swing.JPanel();
        pegCombinationPanel5 = new javax.swing.JPanel();
        guess7 = new javax.swing.JPanel();
        feedbackPanel7 = new javax.swing.JPanel();
        pegCombinationPanel6 = new javax.swing.JPanel();
        guess8 = new javax.swing.JPanel();
        feedbackPanel8 = new javax.swing.JPanel();
        pegCombinationPanel7 = new javax.swing.JPanel();
        colorSelectorPanel = new javax.swing.JPanel();
        correctPeg = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        mastermindMenu = new javax.swing.JMenuBar();
        myGame = new javax.swing.JMenu();
        newGame = new javax.swing.JMenu();
        quitGame = new javax.swing.JMenu();
        help = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 0, 0));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gamePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        guess1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        feedbackPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout feedbackPanel1Layout = new javax.swing.GroupLayout(feedbackPanel1);
        feedbackPanel1.setLayout(feedbackPanel1Layout);
        feedbackPanel1Layout.setHorizontalGroup(
            feedbackPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 67, Short.MAX_VALUE)
        );
        feedbackPanel1Layout.setVerticalGroup(
            feedbackPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 41, Short.MAX_VALUE)
        );

        pegCombinationPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout pegCombinationPanelLayout = new javax.swing.GroupLayout(pegCombinationPanel);
        pegCombinationPanel.setLayout(pegCombinationPanelLayout);
        pegCombinationPanelLayout.setHorizontalGroup(
            pegCombinationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 235, Short.MAX_VALUE)
        );
        pegCombinationPanelLayout.setVerticalGroup(
            pegCombinationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout guess1Layout = new javax.swing.GroupLayout(guess1);
        guess1.setLayout(guess1Layout);
        guess1Layout.setHorizontalGroup(
            guess1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(guess1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(feedbackPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pegCombinationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        guess1Layout.setVerticalGroup(
            guess1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, guess1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(guess1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(feedbackPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pegCombinationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );

        guess2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        feedbackPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout feedbackPanel2Layout = new javax.swing.GroupLayout(feedbackPanel2);
        feedbackPanel2.setLayout(feedbackPanel2Layout);
        feedbackPanel2Layout.setHorizontalGroup(
            feedbackPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 67, Short.MAX_VALUE)
        );
        feedbackPanel2Layout.setVerticalGroup(
            feedbackPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 41, Short.MAX_VALUE)
        );

        pegCombinationPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout pegCombinationPanel1Layout = new javax.swing.GroupLayout(pegCombinationPanel1);
        pegCombinationPanel1.setLayout(pegCombinationPanel1Layout);
        pegCombinationPanel1Layout.setHorizontalGroup(
            pegCombinationPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 235, Short.MAX_VALUE)
        );
        pegCombinationPanel1Layout.setVerticalGroup(
            pegCombinationPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout guess2Layout = new javax.swing.GroupLayout(guess2);
        guess2.setLayout(guess2Layout);
        guess2Layout.setHorizontalGroup(
            guess2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(guess2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(feedbackPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pegCombinationPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        guess2Layout.setVerticalGroup(
            guess2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, guess2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(guess2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(feedbackPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pegCombinationPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );

        guess3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        feedbackPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout feedbackPanel3Layout = new javax.swing.GroupLayout(feedbackPanel3);
        feedbackPanel3.setLayout(feedbackPanel3Layout);
        feedbackPanel3Layout.setHorizontalGroup(
            feedbackPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 67, Short.MAX_VALUE)
        );
        feedbackPanel3Layout.setVerticalGroup(
            feedbackPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 41, Short.MAX_VALUE)
        );

        pegCombinationPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout pegCombinationPanel2Layout = new javax.swing.GroupLayout(pegCombinationPanel2);
        pegCombinationPanel2.setLayout(pegCombinationPanel2Layout);
        pegCombinationPanel2Layout.setHorizontalGroup(
            pegCombinationPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 235, Short.MAX_VALUE)
        );
        pegCombinationPanel2Layout.setVerticalGroup(
            pegCombinationPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout guess3Layout = new javax.swing.GroupLayout(guess3);
        guess3.setLayout(guess3Layout);
        guess3Layout.setHorizontalGroup(
            guess3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(guess3Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(feedbackPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pegCombinationPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        guess3Layout.setVerticalGroup(
            guess3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, guess3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(guess3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(feedbackPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pegCombinationPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );

        guess4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        feedbackPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout feedbackPanel4Layout = new javax.swing.GroupLayout(feedbackPanel4);
        feedbackPanel4.setLayout(feedbackPanel4Layout);
        feedbackPanel4Layout.setHorizontalGroup(
            feedbackPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 67, Short.MAX_VALUE)
        );
        feedbackPanel4Layout.setVerticalGroup(
            feedbackPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 41, Short.MAX_VALUE)
        );

        pegCombinationPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout pegCombinationPanel3Layout = new javax.swing.GroupLayout(pegCombinationPanel3);
        pegCombinationPanel3.setLayout(pegCombinationPanel3Layout);
        pegCombinationPanel3Layout.setHorizontalGroup(
            pegCombinationPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 235, Short.MAX_VALUE)
        );
        pegCombinationPanel3Layout.setVerticalGroup(
            pegCombinationPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout guess4Layout = new javax.swing.GroupLayout(guess4);
        guess4.setLayout(guess4Layout);
        guess4Layout.setHorizontalGroup(
            guess4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(guess4Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(feedbackPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pegCombinationPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        guess4Layout.setVerticalGroup(
            guess4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, guess4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(guess4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(feedbackPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pegCombinationPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );

        guess5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        feedbackPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout feedbackPanel5Layout = new javax.swing.GroupLayout(feedbackPanel5);
        feedbackPanel5.setLayout(feedbackPanel5Layout);
        feedbackPanel5Layout.setHorizontalGroup(
            feedbackPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 67, Short.MAX_VALUE)
        );
        feedbackPanel5Layout.setVerticalGroup(
            feedbackPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 41, Short.MAX_VALUE)
        );

        pegCombinationPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout pegCombinationPanel4Layout = new javax.swing.GroupLayout(pegCombinationPanel4);
        pegCombinationPanel4.setLayout(pegCombinationPanel4Layout);
        pegCombinationPanel4Layout.setHorizontalGroup(
            pegCombinationPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 235, Short.MAX_VALUE)
        );
        pegCombinationPanel4Layout.setVerticalGroup(
            pegCombinationPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout guess5Layout = new javax.swing.GroupLayout(guess5);
        guess5.setLayout(guess5Layout);
        guess5Layout.setHorizontalGroup(
            guess5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(guess5Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(feedbackPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pegCombinationPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        guess5Layout.setVerticalGroup(
            guess5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, guess5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(guess5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(feedbackPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pegCombinationPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );

        guess6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        feedbackPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout feedbackPanel6Layout = new javax.swing.GroupLayout(feedbackPanel6);
        feedbackPanel6.setLayout(feedbackPanel6Layout);
        feedbackPanel6Layout.setHorizontalGroup(
            feedbackPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 67, Short.MAX_VALUE)
        );
        feedbackPanel6Layout.setVerticalGroup(
            feedbackPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 41, Short.MAX_VALUE)
        );

        pegCombinationPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout pegCombinationPanel5Layout = new javax.swing.GroupLayout(pegCombinationPanel5);
        pegCombinationPanel5.setLayout(pegCombinationPanel5Layout);
        pegCombinationPanel5Layout.setHorizontalGroup(
            pegCombinationPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 235, Short.MAX_VALUE)
        );
        pegCombinationPanel5Layout.setVerticalGroup(
            pegCombinationPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout guess6Layout = new javax.swing.GroupLayout(guess6);
        guess6.setLayout(guess6Layout);
        guess6Layout.setHorizontalGroup(
            guess6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(guess6Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(feedbackPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pegCombinationPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        guess6Layout.setVerticalGroup(
            guess6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, guess6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(guess6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(feedbackPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pegCombinationPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );

        guess7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        feedbackPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout feedbackPanel7Layout = new javax.swing.GroupLayout(feedbackPanel7);
        feedbackPanel7.setLayout(feedbackPanel7Layout);
        feedbackPanel7Layout.setHorizontalGroup(
            feedbackPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 67, Short.MAX_VALUE)
        );
        feedbackPanel7Layout.setVerticalGroup(
            feedbackPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 41, Short.MAX_VALUE)
        );

        pegCombinationPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout pegCombinationPanel6Layout = new javax.swing.GroupLayout(pegCombinationPanel6);
        pegCombinationPanel6.setLayout(pegCombinationPanel6Layout);
        pegCombinationPanel6Layout.setHorizontalGroup(
            pegCombinationPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 235, Short.MAX_VALUE)
        );
        pegCombinationPanel6Layout.setVerticalGroup(
            pegCombinationPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout guess7Layout = new javax.swing.GroupLayout(guess7);
        guess7.setLayout(guess7Layout);
        guess7Layout.setHorizontalGroup(
            guess7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(guess7Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(feedbackPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pegCombinationPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        guess7Layout.setVerticalGroup(
            guess7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, guess7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(guess7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(feedbackPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pegCombinationPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );

        guess8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        feedbackPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout feedbackPanel8Layout = new javax.swing.GroupLayout(feedbackPanel8);
        feedbackPanel8.setLayout(feedbackPanel8Layout);
        feedbackPanel8Layout.setHorizontalGroup(
            feedbackPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 67, Short.MAX_VALUE)
        );
        feedbackPanel8Layout.setVerticalGroup(
            feedbackPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 41, Short.MAX_VALUE)
        );

        pegCombinationPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout pegCombinationPanel7Layout = new javax.swing.GroupLayout(pegCombinationPanel7);
        pegCombinationPanel7.setLayout(pegCombinationPanel7Layout);
        pegCombinationPanel7Layout.setHorizontalGroup(
            pegCombinationPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 235, Short.MAX_VALUE)
        );
        pegCombinationPanel7Layout.setVerticalGroup(
            pegCombinationPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout guess8Layout = new javax.swing.GroupLayout(guess8);
        guess8.setLayout(guess8Layout);
        guess8Layout.setHorizontalGroup(
            guess8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(guess8Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(feedbackPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pegCombinationPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        guess8Layout.setVerticalGroup(
            guess8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, guess8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(guess8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(feedbackPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pegCombinationPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout gamePanelLayout = new javax.swing.GroupLayout(gamePanel);
        gamePanel.setLayout(gamePanelLayout);
        gamePanelLayout.setHorizontalGroup(
            gamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gamePanelLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(gamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(guess1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(guess2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(guess3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(guess4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(guess5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(guess6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(guess7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(guess8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        gamePanelLayout.setVerticalGroup(
            gamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gamePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(guess8, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(guess7, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(guess6, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(guess5, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(guess4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(guess3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(guess2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(guess1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        getContentPane().add(gamePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        colorSelectorPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout colorSelectorPanelLayout = new javax.swing.GroupLayout(colorSelectorPanel);
        colorSelectorPanel.setLayout(colorSelectorPanelLayout);
        colorSelectorPanelLayout.setHorizontalGroup(
            colorSelectorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 218, Short.MAX_VALUE)
        );
        colorSelectorPanelLayout.setVerticalGroup(
            colorSelectorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 208, Short.MAX_VALUE)
        );

        getContentPane().add(colorSelectorPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 380, 220, 210));

        correctPeg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout correctPegLayout = new javax.swing.GroupLayout(correctPeg);
        correctPeg.setLayout(correctPegLayout);
        correctPegLayout.setHorizontalGroup(
            correctPegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        correctPegLayout.setVerticalGroup(
            correctPegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        getContentPane().add(correctPeg, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 315, 230, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Anne\\Desktop\\tst2.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 620));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, -10, -1, -1));

        myGame.setText("Game");

        newGame.setText("New Game");
        myGame.add(newGame);

        quitGame.setText("Quit");
        myGame.add(quitGame);

        mastermindMenu.add(myGame);

        help.setText("Help");
        mastermindMenu.add(help);

        setJMenuBar(mastermindMenu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MastermindJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MastermindJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MastermindJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MastermindJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MastermindJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel colorSelectorPanel;
    private javax.swing.JPanel correctPeg;
    private javax.swing.JPanel feedbackPanel1;
    private javax.swing.JPanel feedbackPanel2;
    private javax.swing.JPanel feedbackPanel3;
    private javax.swing.JPanel feedbackPanel4;
    private javax.swing.JPanel feedbackPanel5;
    private javax.swing.JPanel feedbackPanel6;
    private javax.swing.JPanel feedbackPanel7;
    private javax.swing.JPanel feedbackPanel8;
    private javax.swing.JPanel gamePanel;
    private javax.swing.JPanel guess1;
    private javax.swing.JPanel guess2;
    private javax.swing.JPanel guess3;
    private javax.swing.JPanel guess4;
    private javax.swing.JPanel guess5;
    private javax.swing.JPanel guess6;
    private javax.swing.JPanel guess7;
    private javax.swing.JPanel guess8;
    private javax.swing.JMenu help;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuBar mastermindMenu;
    private javax.swing.JMenu myGame;
    private javax.swing.JMenu newGame;
    private javax.swing.JPanel pegCombinationPanel;
    private javax.swing.JPanel pegCombinationPanel1;
    private javax.swing.JPanel pegCombinationPanel2;
    private javax.swing.JPanel pegCombinationPanel3;
    private javax.swing.JPanel pegCombinationPanel4;
    private javax.swing.JPanel pegCombinationPanel5;
    private javax.swing.JPanel pegCombinationPanel6;
    private javax.swing.JPanel pegCombinationPanel7;
    private javax.swing.JMenu quitGame;
    // End of variables declaration//GEN-END:variables
}
